-- 코드를 입력하세요
# SELECT 
#     SUM(CASE WHEN ANIMAL_TYPE = 'Cat' THEN 1 ELSE 0 END) AS Cat,
#     SUM(CASE WHEN ANIMAL_TYPE = 'Dog' THEN 1 ELSE 0 END) AS Dog
# FROM ANIMAL_INS
# order by animal_type asc;

SELECT ANIMAL_TYPE, COUNT(*) AS Count
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY FIELD(ANIMAL_TYPE, 'Cat', 'Dog');
